service: my-express-application

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getLocationKey:
    handler: index.handler
    events:
      - http: 'POST /location/zip'
  getWeather:
    handler: index.handler
    events:
      - http: 'POST /weather'
plugins:
  - serverless-offline
